### ISSUE TITLE
Package Versioning Policy versus Semantic Versioning

### ISSUE THREAD

**Issue by tfausak** [tfausak/tfausak.github.io#117]
Many people on Reddit took issue with me recommending SemVer over the PVP. 

> I totally disagree about SemVer v. PVP Versioning.

https://www.reddit.com/r/haskell/comments/5iok3l/haskell_package_checklist/

I am obviously in favor of SemVer. I wanted some empirical data about Haskell package versioning. I wrote a script that downloads Hackage's package index and looks at the version numbers.

> Found 10642 packages.
> Number of version components => number of packages
> 3 => 4255
> 4 => 4638
> Number of (version components, major versions) => number of packages
> (3,1) => 3747
> (4,1) => 4357

https://gist.github.com/tfausak/98726c8255c5bc5c940e0f4939978a43

I assume that 3 version components means SemVer and 4 version components means the PVP. That's not quite accurate since SemVer requires exactly 3 components but the PVP requires at least 3.

> A package version number SHOULD have the form A.B.C, and MAY optionally have any number of additional components

http://pvp.haskell.org/

Anyway, the PVP is the most popular versioning policy on Hackage. But SemVer is a very close second. 

> Of the 10,642 #Haskell packages on Hackage, 4,638 use the PVP and 4,255 use SemVer.

https://twitter.com/taylorfausak/status/811578904209227776

Most of the packages on Hackage never change their most significant version number. Only 9% have.

> Of the 10,642 #Haskell packages on Hackage, only 921 have ever changed their most significant version number.

https://twitter.com/taylorfausak/status/811579159671668736

6% of PVP packages have ever changed their most significant version number. That's a lot less than the overall rate.

> Of the 4,638 #Haskell packages on Hackage that use the PVP, only 281 have ever changed their most significant version number.

https://twitter.com/taylorfausak/status/811579605278670849

12% of SemVer packages have ever changed their most significant version number. That's a lot more than the overall rate.

> Of the 4,255 #Haskell packages on Hackage that use SemVer, 508 have changed their most significant version number.

https://twitter.com/taylorfausak/status/811580634045026304

Those numbers make SemVer look less stable than the PVP, but it isn't a fair comparison. I need to update the script to look at the first two components of packages that use the PVP and compare that to the first component of packages that use SemVer. 

Even as they are now, the numbers support a point I want to make: The PVP gives unnecessary freedom that most packages don't even use.

**Comment by tfausak** [comment]
Another thing I want to address is which major version packages are using. bytestring is on 0, aeson is on 1, base is on 4, and HTTP is on 4000.

**Comment by alanz** [comment]
There is another side to the preferences between SemVer and PVP.  The hackage/cabal solver is explicitly designed to work well with the PVP, meaning your are more likely to get a viable build plan if more packages use PVP.

This is especially important if your use case does not fit squarely into a stack snapshot, if e.g. you are required to use anything outside of the snapshot.

**Comment by tfausak** [comment]
I updated the Gist to include information about the major version numbers.

> Current major version => number of packages
0 => 8585
1 => 1411
2 => 270
3 => 130
(Number of version components, current major version) => number of packages
(3,0) => 3199
(3,1) => 700
(3,2) => 130
(3,3) => 59
(4,0) => 4037
(4,1) => 415
(4,2) => 91
(4,3) => 47

Out of 10,643 packages, 8,585 are on major version 0. That's 81%. For the 4,639 PVP packages, 4,037 or 87% are on 0. For the 4,255 SemVer packages, 3,199 or 75% are on 0.

**Comment by tfausak** [comment]
> The hackage/cabal solver is explicitly designed to work well with the PVP, meaning your are more likely to get a viable build plan if more packages use PVP.

I've heard that elsewhere too. Can you help me understand how the solver works well with the PVP? I am not familiar with how Cabal's solver works.

**Comment by ezyang** [comment]
It doesn't really have anything to do with the solver; it's just that people are encouraged to write their version bounds in the form of `>= x.y && < x'.y'`. The fact that *two* components are given means that it is following PVP, not semver.

Maybe a good test for this is to find out, out of all upper bounds in build-depends, which ones specify two components, and which ones specify only one. Ones that specify two components are probably not following semver, because semver says that changes to 'y' are not breaking.

**Comment by alanz** [comment]
I am not an expert, but I understand the core of it is that if the first two version numbers stay the same, then the API stays the same. So any dependency having the same first 2 digits should be usable.

Unfortunately this aspect is not fully automatic at present, so there us a need to manually specify version bounds on each dependency to constrain it to the set promised by adherence to PVP.

There is currently a discussion process around making this more automatic at https://github.com/haskell/ecosystem-proposals/pull/1

**Comment by tfausak** [comment]
I see.

If you were really following the PVP, wouldn't your bounds need to be `>= a.b.c && < a'.b'`? You need at least some functionality provided by the minor version `c` and you know that you'll keep working until the major version changes to `a'.b'`. 

Checking upper bounds would be a good way to do. I have two problems with it, both of which are minor: (1) Parsing Cabal files is going to be slower than checking path segments in a `tar` file; and (2) I use `--pvp-bounds=both` when releasing packages even though I use SemVer. I could see which bounds other packages put on some package, but that assumes the bounds are accurate.

**Comment by gbaz** [comment]
> Most of the packages on Hackage never change their most significant version number. Only 9% have.

I would also bet most packages on hackage have only had relatively few releases. You'll have a long tail of packages that only see a few releases compared to those that make it to "long lived, stable".

As discussed elsewhere, looking at version number components as you do doesn't tell you anything about semver vs. pvp -- many packages using pvp only use three components. So these numbers are not very much use at all. If Haskell is indeed nearly entirely standardized on pvp (and I would contend that it is), then moving to a slightly different system seems like it would induce an enormous amount of pain and confusion for little-to-no  material benefit.

**Comment by ezyang** [comment]
Yes. In practice, people often write `>= a.b` because they only use features that were available in `a.b.0`, but it would be strictly more accurate to always put the minor version in. But it causes errors so you see people often adding that minor version number in to fix things. Lower bounds don't get exercised as much because the depsolvers prefer later versions.

**Comment by tfausak** [comment]
I updated the Gist to include the number of releases as well. 

> Number of releases => number of packages
1 => 2168
2 => 1716
3 => 1359
4 => 945
5 => 688
6 => 532
7 => 448
8 => 341
9 => 295

80% of packages have fewer than 10 releases.

**Comment by tfausak** [comment]
After reading replies here, on Reddit, and on Twitter, it has become apparent that I must be very careful in how I interpret this data. Saying "3 version parts means SemVer" and "4 version parts means PVP" is inaccurate. It's true that SemVer requires exactly 3 version parts, but the PVP only specifies *at least* 3 version parts. Also some packages that *do* follow the PVP don't always use the same number of parts; look at [lens](https://hackage.haskell.org/package/lens) for an example. 

At this point, the things I can say about the data are pretty boring:

- Most packages have 3 or 4 version parts. It's about an even split.
- Most packages have never changed their major version number. 
- If the package has 4 version parts, it's less likely to change the most significant part (compared to 3 parts).
- Most packages are on major version 0. 
- If the package has 4 version parts, it's more likely to be on major version 0 (compared to 3 parts). 
- Most packages have fewer than 10 releases.

**Comment by rwbarton** [comment]
> Of the 10,642 #Haskell packages on Hackage, only 921 have ever changed their most significant version number.

Without consulting any statistics, what proportion of packages following SemVer would you expect to have never made any incompatible API changes?

(Maybe it would be best to ignore packages with fewer than, say, three released versions.)

**Comment by tfausak** [comment]
I've already linked all the interesting tweets. Here's the Reddit thread about them: https://www.reddit.com/r/haskell/comments/5jlgxe/of_the_10642_haskell_packages_on_hackage_4638_use/

Since this post deals with version numbers, invariably someone will bring up this recent Rich Hickey video: https://www.youtube.com/watch?v=oyLBGkS5ICk

> what proportion of packages following SemVer would you expect to have never made any incompatible API changes?

I would expect a very small number of SemVer packages to be on a major version above 1. Pulling a number out of a hat, I'd say I expect... 2% to have ever made a breaking change after reaching version 1.0.0.

**Comment by tfausak** [comment]
> It's true that SemVer requires exactly 3 version parts, but the PVP only specifies at least 3 version parts.

In fact, the PVP only *recommends* at least 3 parts. This has some interesting consequences:

- It is valid per the PVP to have a version `1`. 
- It is also valid per the PVP to signal breaking changes by going from version `1` to `1.0`. That's because `1` is less than `1.0` according to Data.Version. 
  - Hackage recently added a check to prevent users from uploading package versions like this. See https://github.com/haskell/hackage-server/pull/518 and https://github.com/haskell/cabal/pull/3515#issuecomment-231714012.
  - This can also wreak havoc with version bounds since `>= A.B` and `>= A.B.0` don't mean the same thing. This affects `== A.B.*` constructs too since they mean `>= A.B && < A.(B+1)`. See https://github.com/fpco/stackage/issues/2143#issuecomment-268966698. 
- It's valid to use a different number of parts for each release. This is basically what the lens package does. By convention the missing components are assumed to be 0, but that's not exactly true. 

SemVer avoids these shenanigans by requiring exactly 3 parts.

**Comment by mightybyte** [comment]
The fact that 8585 packages currently have an initial version number of "0" by itself suggests that PVP is likely to be the most commonly used scheme.  Any package that has a current major version of "0" and has ever made a backwards-incompatible change should be assumed to be following the PVP.  The Haskell community is known for not having an incredibly strong commitment to backwards compatibility so I think it's likely that most packages that have more than a 3 or 4 releases have probably made a backwards-incompatible change.  That's not guaranteed, but it seems quite likely.

This tells us nothing about the rest of the packages.  But I can think of a number of packages that do not currently have a first version number of "0" that do follow the PVP.  So I think it's quite reasonable to say that many of the remaining 2058 packages may also follow the PVP.

Side note:  In my 6+ years of professional Haskell development there I have not encountered a single problem with the "shenanigans" you mention relating to the way the PVP treats version `1` vs `1.0`, the optionality of version numbers, etc.  The stackage issue #2143 that you mention is the first one I've ever seen, so I think the words "wreak havoc" are a bit of an exaggeration.  It certainly could be worthwhile to think about whether changing that would improve things.  But switching to SemVer is definitely not the right solution to that problem.

**Comment by tfausak** [comment]
> Any package that has a current major version of "0" and has ever made a backwards-incompatible change should be assumed to be following the PVP. 

I disagree. Can you explain why this should be the case? SemVer specifically allows for breaking changes when the major version number is 0: ["Major version zero (0.y.z) is for initial development. Anything may change at any time."](http://semver.org/spec/v2.0.0.html#spec-item-4)

If I understand you correctly, you are saying that packages with major version 0 probably use the PVP. Then, also, packages with major version *not* 0 probably use the PVP as well. 

I think that it is not possible to say anything in general about which versioning scheme packages use based on their major version number. This is similar to how I (now) think that it is not possible to say anything in general about which versioning scheme packages use based on the number of version components.

> I have not encountered a single problem with the "shenanigans" you mention relating to the way the PVP treats version 1 vs 1.0

I haven't either! I hope you'll excuse me for being imprecise on this issue thread, which amounts to a scratch pad of ideas for a blog post. However I stand by what I said: "This **can** also wreak havoc with version bounds". I didn't mean to imply that this is a widespread problem. In fact, I even linked to a comment that shows this has only happened 41 times! What I meant to say is that it's both possible *and allowed* (per the PVP) to start at version 1, then make a breaking change and release that as version 1.0. Does that sound accurate to you? 

> switching to SemVer is definitely not the right solution to that problem

Can you explain why you think that? I think that SemVer would solve this problem. Hackage has solved this problem by preventing users from uploading packages that increment their version number in this way, even though it is in accordance with the PVP. Fixing the PVP would also solve this particular problem, but I'm not holding my breath for this issue to be resolved: https://github.com/haskell/pvp/issues/4

**Comment by tfausak** [comment]
Although this is obviously an [appeal to the people](https://en.wikipedia.org/wiki/Argumentum_ad_populum), the PVP is specific to Haskell.

- JavaScript's npm uses SemVer: https://docs.npmjs.com/getting-started/semantic-versioning.
- Python allows for a wide range of versioning schemes and can accommodate both SemVer and the PVP: https://www.python.org/dev/peps/pep-0440/#public-version-identifiers. It has a specific provision for avoiding the problem of adding ".0" segments that affects the PVP. It goes on to encourage following the PVP. It's version range specifiers (like `~= 1.2`) work like SemVer, not the PVP. 
- Ruby's RubyGems uses SemVer: http://guides.rubygems.org/patterns/#semantic-versioning.
- PHP's Packagist recommends SemVer: https://packagist.org/about#managing-package-versions. 
- Elm uses SemVer: https://github.com/elm-lang/elm-package/blob/1a364bc/README.md#version-rules.
- PureScript's Pursuit recommends using Pulp for version numbers: https://pursuit.purescript.org/help. Pulp uses SemVer: https://github.com/bodil/pulp/blob/abf457d/src/Pulp/VersionBump.purs.
- Java's Maven recommends SemVer: http://central.sonatype.org/pages/requirements.html#correct-coordinates. 
- Clojure's Leiningen recommends SemVer: https://github.com/technomancy/leiningen/blob/705b1a7/doc/FAQ.md#faq.
- .NET's NuGet doesn't recommend any versioning scheme: https://docs.nuget.org/ndocs/create-packages/dependency-versions. It does avoid the problem the PVP has with ".0" segments. They seem to want to move toward SemVer: http://blog.nuget.org/20140924/supporting-semver-2.0.0.html.

**Comment by mightybyte** [comment]
@tfausak Oh, that's a good point.  I had forgotten about SemVer's special treatment of `0.`.  With that in mind I guess you have to disregard my above argument about leading 0s.  But actually, that is a stronger argument against SemVer.  If a package has a `0.` prefix, SemVer says you know nothing.  We don't want that.  The whole point of having a scheme in the first place is so that the version scheme can distinguish breaking and non-breaking changes.  There shouldn't be an escape hatch.  You don't want `cabal install foo` to be reliable only in some situations.  It should work all the time.

**Comment by vincenthz** [comment]
@mightybyte if you want something reliable, you should try `stack` ! :trollface:

**Comment by ezyang** [comment]
@tfausak Did you ever end up doing the experiment where you checked how many upper bounds looked like `< 2.3` versus `< 2`?

**Comment by tfausak** [comment]
Not yet, but @snoyberg provided [this Gist](https://gist.github.com/snoyberg/a262fc6bcfae68988c772b05d8744ea8/886236480e6ff5f7912a074c686e87edc2b57838), which does something similar. It checks for both upper and lower bounds. 

> Total unique packages: 10644
Total PVP following packages in latest revision: 3113
PVP follower percent: 29%

**Comment by ezyang** [comment]
OK, but @snoyberg is measuring something different: PVP compliance as defined by having upper and lower bounds (in fact, I think he's assuming that any packages that use bounds are following PVP.)

I believe the correct distinction for PVP versus semver is this: if a package has a bounded like `< 2`, it is using semver; if it is bounded like `< 1.8`, it is using PVP.

**Comment by mightybyte** [comment]
@vincenthz I'd rather not do manual dependency resolution.

**Comment by tfausak** [comment]
You're right. I meant to provide Snoyman's script as a jumping-off point for anything else that wants to analyze the actual Cabal files. So far my scripts have only looked at file paths in the package index tarball. 

We're treading into the territory of "PVP-the-versioning-scheme" versus "PVP-the-dependency-version-constraint-specification". SemVer doesn't actually specify how you should constrain your dependencies. It follows naturally from the spec that you'll probably end up with `>= 1.2 && < 2`, but the spec doesn't require it. I don't particularly care how you constrain your dependencies. 

> if a package is upper bounded like < 2 (only one version part), it is using semver; if it is bounded like < 1.8 (two version parts), it is using PVP.

I agree. It tells you if the package targeted by those constraints is (probably) using SemVer or the PVP. By collecting that information over the whole package index, we might have a reasonable idea of which packages use the PVP.

On the other hand, I'll bet that constraints like `base >= 4.6 && < 5` are pretty common even though the base package uses the PVP.

**Comment by mightybyte** [comment]
> We're treading into the territory of "PVP-the-versioning-scheme" versus "PVP-the-dependency-version-constraint-specification". SemVer doesn't actually specify how you should constrain your dependencies. It follows naturally from the spec that you'll probably end up with >= 1.2 && < 2, but the spec doesn't require it. I don't particularly care how you constrain your dependencies.

If you don't constrain your dependencies, I don't see any point in having a versioning scheme at all.  With no version bounds version numbers don't need to have any meaning because they aren't being used for anything.  We might as well just use ascending integers and be done with it.  In that state of the world anything more would be a waste of time.

If you accept the above statement, then the contrapositive also holds: If we think a versioning scheme has value, then we should use version bounds on our dependencies.

**Comment by tfausak** [comment]
I didn't say you *shouldn't* constraint your dependencies. I said I don't care how you do it. Specifically, for the purposes of this post (and therefore this discussion), I am concerned with how you assign version numbers to your packages rather than how you constrain the version numbers of your package's dependencies. 

I want to avoid talking about version constraints because it will invariably devolve into a Cabal versus Stack flame war. Unfortunately it's hard to specify that I mean "the 'version numbers' part of the PVP spec" versus "the 'dependencies in Cabal' part of the PVP spec". At least with the term "cabal" we have "Cabal the library" and "cabal(-install) the tool". 

On the other hand, I think it's fine to talk about how a versioning scheme affects constraints. For example, many of my packages work with (at least) `aeson-0.11.2.1` and `aeson-1.0.2.1`. The most accurate version bounds for that are `aeson (>= 0.11.2 && < 0.12) || (>= 1.0.2 && < 1.1)`. I think you'll agree that's cumbersome at best. I usually constrain it as `aeson >= 0.11 && < 1.1`. I think you'll agree that's inaccurate but also much easier to type. 

I'm aware of the possibility that `aeson-0.12.0.0` could be released and be neither backwards-compatible with 0.11 nor forwards-compatible with 1.0. It seems extremely unlikely to me, though. That's why I take the shortcut with my constraints.

If Aeson used SemVer, my version constraint would probably look like `aeson >= 11.0 && < 13` (assuming 0.11 becomes 11.x and 1.0 becomes 12.x). There's no room for anything bad to sneak into that version range. And it's the easiest thing to type. (It would be even easier if Cabal supported more interesting specifiers like `^1.2.3` or `~1.2.3`.)

**Comment by ezyang** [comment]
You make a good point that in PVP style versioning, it is possible for a package to be compatible with 0.11 and 1.0, but not with 0.12. This can even be true if 1.0 is released after 0.12 (maybe it undid the BC breaking change). But in this case it's obvious that the accurate bounds should be `< 0.11 || >= 1.0 && < 1.1`. So the only problem is if 1.12 was released after 1.0. I think there is an informal expectation that once you bump x, you'll never bump the y on an older x-release series (for example, now that GHC 8.0 is out, there will never be a 7.12 release). This isn't codified in the PVP, but arguably it should.

But returning to the original question of the conversation, the claim we are trying to assess is, "The Haskell community generally believes packages are PVP versioned rather than semantically versioned." I think we can talk about semver versus PVP without wading into the Stack/cabal-install discussion: all I am saying is that *if* there is an upper version bound (whether or not you put an upper bound is a cabal-install/Stack question), a claim is being made about whether or not the package follows PVP or semver. If there is no upper bound, you don't get any information, but that's OK.
