### ISSUE TITLE
Announce ActiveInteraction v2.0.0

### ISSUE THREAD

**Issue by tfausak** [tfausak/tfausak.github.io#65]
I think versions 2.0.0 and 1.6.0 of ActiveInteraction are ready to be released. I should work with @AaronLasseigne to write a blog post announcing them. 
https://github.com/orgsync/active_interaction/blob/v2.0.0/CHANGELOG.md
https://github.com/orgsync/active_interaction/blob/gh-277/CHANGELOG.md

We announced version 1.0.0 more than a year ago! Time flies.
http://taylor.fausak.me/2014/01/23/confidently-manage-business-logic-with-active-interaction/

**Comment by AaronLasseigne** [comment]
:+1:

**Comment by tfausak** [comment]
I really like how [RSpec 3](http://rspec.info/blog/2013/07/the-plan-for-rspec-3/) announced their changes.
